//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiCoffe.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\sqlexpress;Initial Catalog=QLCF;Integrated Security=True")]
        public string QLCFConnectionString {
            get {
                return ((string)(this["QLCFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        public string QLCPConnectionString {
            get {
                return ((string)(this["QLCPConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("34, 36, 49")]
        public global::System.Drawing.Color typeBack1 {
            get {
                return ((global::System.Drawing.Color)(this["typeBack1"]));
            }
            set {
                this["typeBack1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 168, 255")]
        public global::System.Drawing.Color typeBack2 {
            get {
                return ((global::System.Drawing.Color)(this["typeBack2"]));
            }
            set {
                this["typeBack2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("78, 184, 206")]
        public global::System.Drawing.Color typeBack3 {
            get {
                return ((global::System.Drawing.Color)(this["typeBack3"]));
            }
            set {
                this["typeBack3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("78, 184, 206")]
        public global::System.Drawing.Color typeFore1 {
            get {
                return ((global::System.Drawing.Color)(this["typeFore1"]));
            }
            set {
                this["typeFore1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color typeFore2 {
            get {
                return ((global::System.Drawing.Color)(this["typeFore2"]));
            }
            set {
                this["typeFore2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("34, 36, 49")]
        public global::System.Drawing.Color typeFore3 {
            get {
                return ((global::System.Drawing.Color)(this["typeFore3"]));
            }
            set {
                this["typeFore3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool greeting {
            get {
                return ((bool)(this["greeting"]));
            }
            set {
                this["greeting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bye {
            get {
                return ((bool)(this["bye"]));
            }
            set {
                this["bye"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool soundTrack {
            get {
                return ((bool)(this["soundTrack"]));
            }
            set {
                this["soundTrack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool click {
            get {
                return ((bool)(this["click"]));
            }
            set {
                this["click"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool appearance {
            get {
                return ((bool)(this["appearance"]));
            }
            set {
                this["appearance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool notification {
            get {
                return ((bool)(this["notification"]));
            }
            set {
                this["notification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string companyIntroduce {
            get {
                return ((string)(this["companyIntroduce"]));
            }
            set {
                this["companyIntroduce"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("549 Xô Viết Nghệ Tĩnh - P.26 - Q.Bình Thạnh - TP.HCM - Việt Nam")]
        public string companyAddress {
            get {
                return ((string)(this["companyAddress"]));
            }
            set {
                this["companyAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("549 Xô Viết Nghệ Tĩnh - P.26")]
        public string companyAddressBill1 {
            get {
                return ((string)(this["companyAddressBill1"]));
            }
            set {
                this["companyAddressBill1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(+84) 0943 144 178")]
        public string companyPhone1 {
            get {
                return ((string)(this["companyPhone1"]));
            }
            set {
                this["companyPhone1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(+84) 0000 000 000")]
        public string companyPhone2 {
            get {
                return ((string)(this["companyPhone2"]));
            }
            set {
                this["companyPhone2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sotayvaodoi@gmail.com")]
        public string companyEmail1 {
            get {
                return ((string)(this["companyEmail1"]));
            }
            set {
                this["companyEmail1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("anonymous220011@gmail.com")]
        public string companyEmail2 {
            get {
                return ((string)(this["companyEmail2"]));
            }
            set {
                this["companyEmail2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7410 852 9630 000 - Nguyễn Ngọc Hiếu - Chi nhánh TechComBank Bình Thạnh")]
        public string companyBank1 {
            get {
                return ((string)(this["companyBank1"]));
            }
            set {
                this["companyBank1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7410 852 9630 000 - Nguyễn Ngọc Hiếu - Chi nhánh TechComBank Bình Thạnh")]
        public string companyBank2 {
            get {
                return ((string)(this["companyBank2"]));
            }
            set {
                this["companyBank2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.facebook.com/zi.anonymous.zi")]
        public string linkFacebook {
            get {
                return ((string)(this["linkFacebook"]));
            }
            set {
                this["linkFacebook"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.youtube.com/channel/UCi0aeFqCM7PDf1QPltsS4gw?view_as=subscriber")]
        public string linkYoutube {
            get {
                return ((string)(this["linkYoutube"]));
            }
            set {
                this["linkYoutube"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sites.google.com/view/zitech-us-1611061206/trang-ch%E1%BB%A7")]
        public string linkWebsite {
            get {
                return ((string)(this["linkWebsite"]));
            }
            set {
                this["linkWebsite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.instagram.com/zi1611061206/")]
        public string linkInstagram {
            get {
                return ((string)(this["linkInstagram"]));
            }
            set {
                this["linkInstagram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://aboutme.google.com/")]
        public string linkGooglePlus {
            get {
                return ((string)(this["linkGooglePlus"]));
            }
            set {
                this["linkGooglePlus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ipAdress {
            get {
                return ((string)(this["ipAdress"]));
            }
            set {
                this["ipAdress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("163")]
        public int drinksWidth {
            get {
                return ((int)(this["drinksWidth"]));
            }
            set {
                this["drinksWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210")]
        public int drinksHeigh {
            get {
                return ((int)(this["drinksHeigh"]));
            }
            set {
                this["drinksHeigh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("133")]
        public int tableWidth {
            get {
                return ((int)(this["tableWidth"]));
            }
            set {
                this["tableWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("133")]
        public int tableHeigh {
            get {
                return ((int)(this["tableHeigh"]));
            }
            set {
                this["tableHeigh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 168, 255")]
        public global::System.Drawing.Color tableBackColorTemp {
            get {
                return ((global::System.Drawing.Color)(this["tableBackColorTemp"]));
            }
            set {
                this["tableBackColorTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color tableForeColor {
            get {
                return ((global::System.Drawing.Color)(this["tableForeColor"]));
            }
            set {
                this["tableForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color drinkBackColor {
            get {
                return ((global::System.Drawing.Color)(this["drinkBackColor"]));
            }
            set {
                this["drinkBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color drinkForeColorName {
            get {
                return ((global::System.Drawing.Color)(this["drinkForeColorName"]));
            }
            set {
                this["drinkForeColorName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color drinkForeColorPrice {
            get {
                return ((global::System.Drawing.Color)(this["drinkForeColorPrice"]));
            }
            set {
                this["drinkForeColorPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color tableBackColorFull {
            get {
                return ((global::System.Drawing.Color)(this["tableBackColorFull"]));
            }
            set {
                this["tableBackColorFull"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 122, 204")]
        public global::System.Drawing.Color titleBackColor {
            get {
                return ((global::System.Drawing.Color)(this["titleBackColor"]));
            }
            set {
                this["titleBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color titleForeColor {
            get {
                return ((global::System.Drawing.Color)(this["titleForeColor"]));
            }
            set {
                this["titleForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 122, 204")]
        public global::System.Drawing.Color footerBackColor {
            get {
                return ((global::System.Drawing.Color)(this["footerBackColor"]));
            }
            set {
                this["footerBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color footerForeColor {
            get {
                return ((global::System.Drawing.Color)(this["footerForeColor"]));
            }
            set {
                this["footerForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("34, 36, 49")]
        public global::System.Drawing.Color currentThemeColor {
            get {
                return ((global::System.Drawing.Color)(this["currentThemeColor"]));
            }
            set {
                this["currentThemeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("34, 36, 49")]
        public global::System.Drawing.Color theme1 {
            get {
                return ((global::System.Drawing.Color)(this["theme1"]));
            }
            set {
                this["theme1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 122, 204")]
        public global::System.Drawing.Color theme2 {
            get {
                return ((global::System.Drawing.Color)(this["theme2"]));
            }
            set {
                this["theme2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color theme3 {
            get {
                return ((global::System.Drawing.Color)(this["theme3"]));
            }
            set {
                this["theme3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color theme4 {
            get {
                return ((global::System.Drawing.Color)(this["theme4"]));
            }
            set {
                this["theme4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color theme5 {
            get {
                return ((global::System.Drawing.Color)(this["theme5"]));
            }
            set {
                this["theme5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int sexStaff {
            get {
                return ((int)(this["sexStaff"]));
            }
            set {
                this["sexStaff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string nameStaff {
            get {
                return ((string)(this["nameStaff"]));
            }
            set {
                this["nameStaff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string addressStaff {
            get {
                return ((string)(this["addressStaff"]));
            }
            set {
                this["addressStaff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string phoneStaff {
            get {
                return ((string)(this["phoneStaff"]));
            }
            set {
                this["phoneStaff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int positionStaff {
            get {
                return ((int)(this["positionStaff"]));
            }
            set {
                this["positionStaff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usernameStaff {
            get {
                return ((string)(this["usernameStaff"]));
            }
            set {
                this["usernameStaff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int speakerVolumn {
            get {
                return ((int)(this["speakerVolumn"]));
            }
            set {
                this["speakerVolumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int speakerRate {
            get {
                return ((int)(this["speakerRate"]));
            }
            set {
                this["speakerRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Goodbye, See you later!")]
        public string goodbye {
            get {
                return ((string)(this["goodbye"]));
            }
            set {
                this["goodbye"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Welcome to Coffee Shop Managerment. How are you ,today?\"")]
        public string welcome {
            get {
                return ((string)(this["welcome"]));
            }
            set {
                this["welcome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool allowLoad {
            get {
                return ((bool)(this["allowLoad"]));
            }
            set {
                this["allowLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime birthStaff {
            get {
                return ((global::System.DateTime)(this["birthStaff"]));
            }
            set {
                this["birthStaff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string idCardStaff {
            get {
                return ((string)(this["idCardStaff"]));
            }
            set {
                this["idCardStaff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color typeBackOff {
            get {
                return ((global::System.Drawing.Color)(this["typeBackOff"]));
            }
            set {
                this["typeBackOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q.Bình Thạnh - TP.HCM - Việt Nam")]
        public string companyAddressBill2 {
            get {
                return ((string)(this["companyAddressBill2"]));
            }
            set {
                this["companyAddressBill2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VND")]
        public string currencySymbol {
            get {
                return ((string)(this["currencySymbol"]));
            }
            set {
                this["currencySymbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vi-VN")]
        public string language {
            get {
                return ((string)(this["language"]));
            }
            set {
                this["language"] = value;
            }
        }
    }
}
